# -*- coding: utf-8 -*-
"""Assignment3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Q0BzAmsWpxJlSO5wIQUTdPJuXNLp5L8
"""

#Question 1
def numbers():
  for i in range(1,11):
    print(i)
numbers()
print()
#Question 2
def number(num):
  for i in range(1,num+1):
    print(i)
number(20)
#Question 3
def reverse(num1):
  num1=str(num1)
  n=len(num1)
  for i in range(-1,-(n+1),-1):
    print(num1[i],end="")
reverse(80583)
print( )
#Question 4
def count(num2):
  num2=str(num2)
  length=len(num2)
  print("The number of digits in",num2,"are",length)
count(9871922)
#Question 5
def pallindrome(num3):
  num3=str(num3)
  if num3==num3[::-1]:
    print(num3,"is a pallindrome")
  else:
    print(num3,"is not a pallindrome")
pallindrome(69096)
#Question 6
def fibbonacci(num4):
  a=0
  b=1
  print(a)
  print(b)
  for i in range(0,num4-2):
    c=a+b
    a=b
    b=c
    print(c)
number1=int(input("Enter the number of terms for which you want to calculate the fibbonacci series: "))
fibbonacci(number1)
#Question 7
def sum1(a,b):
   print("sum is ",a+b)
def diff(a,b):
  print("difference is ",a+b)
def multiply(a,b):
  print("product is ",a*b)

def divide(a,b):
  if b==0:
     print("Division by zero is not allowed")
  else:
    print("Quotient is ",a/b)
print("Calculator")
print("1. Addition")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
wish= int(input("Enter your choice from 1/2/3/4: "))
numbl = float(input("Enter first number: "))
numb2 = float(input("Enter second number: "))
if wish == 1:
   sum1(numbl,numb2)
elif wish == 2:
  diff(numbl,numb2)
elif wish == 3:
  multiply(numbl,numb2)
elif wish== 4:
  divide(numb1,numb2)
else:
  print("Invalid Choice")
#Question 8
roll_no=int(input("Enter student roll number:"))
name=input("Enter  student name: ")
program=input("Enter student program: ")
branch=input("Enter student branch: ")
sem=int(input("Enter student semester: "))
email=input("Enter student email: ")
phone=int(input("Enter student phone number: "))
fileobj=open("student.txt","w")
fileobj.write("Roll No: "+str(roll_no)+"\n")
fileobj.write("Name: "+name+"\n")
fileobj.write("Program: "+program+"\n")
fileobj.write("Branch: "+branch+"\n")
fileobj.write("Semester: "+str(sem)+"\n")
fileobj.write("Email: "+email+"\n")
fileobj.write("Phone: "+str(phone)+"\n")
fileobj.close()
#Question 9
fileobj1=open("student.txt","r")
data=fileobj1.read()
print(data)
fileobj1.close()
#Question 10
try:
    a=int(input("Enter numerator: "))
    b=int(input("Enter denominator: "))
    quotient=a/b
    print("Quotient=", result)
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")
#Question 11
class Student:
    def __init__(self,name,marks):
        self.name=name
        self.marks=marks
S1=Student("Simran","18")
print("Name:",S1.name)
print("Marks:",S1.marks)